### PR TITLE
Chore/enhance test suite

### PR DESCRIPTION
**Pull request by DenuxPlays**
This adds a second workspace to handle acceptance tests.

To add a test we simply create a new crate within this workspace and simulate how the end-user would expect the macro to function.
This also adds the ability to use test-driven development.

This should speed up development.

### CODE REVIEW

**Comment by DenuxPlays** [comment]
I did this because we could simply add a second crate to test this pr: https://github.com/ProbablyClem/utoipauto/pull/38

**Comment by DenuxPlays** [comment]
Note:

Please do not merge

I want to define the msrv, toolchain etc.

**Review by ProbablyClem — APPROVED** [review]
Good idea

**Comment by DenuxPlays** [comment]
Tooling will be done after #40 is merged.
Because then we can simlink rustfmt.toml etc. into the directory to keep it consistent

**Pull request merged**
