### PR TITLE
Correctly convert paths containing 'src' to module paths

### PR DESCRIPTION
**Pull request by tnibler**
When using `utoipa` in a subcrate of a cargo workspace, macro invocations may look like:

```
#[utoipauto(paths = "./subcrate/src/module/thing.rs")]
```

Before this change, expanded code looks like:

```
        let mut openapi = utoipa::openapi::OpenApiBuilder::new()
            .info(...)
            .paths(
                utoipa::openapi::path::PathsBuilder::new()
                    .path(
                        crate::src::module::thing::__path_get_endpoint::path(),
                        crate::src::module::thing::__path_get_endpoint::path_item(
                            Some("crate::src::module::thing"),
                        ),
                    ),
            )
            .build();
```

where `crate::src::module::thing` is incorrect and should be `crate::module::thing`.

This commit changes the path -> module path conversion logic to the following:
 
 - replace the first path segment with `crate`
 - if the second segment is `src`, remove it
 - keep all other segments as they are

### CODE REVIEW

**Comment by ProbablyClem** [comment]
Thanks for your contribution, however, you can't use local deps otherwise it can't be published to crates.io.
There must be a way but I couln't find it...
Can you submit a new PR with just the parsing from enum and add tests cases.
Thanks

**Comment by tnibler** [comment]
Woops sorry didn't realize. Now it's only the one change.

**Comment by ProbablyClem** [comment]
The /src issue has been fixed with a replace in the latest 0.1.2 release.
Why would your solution be better ?
Btw, please add tests when you submit a PR

**Comment by ProbablyClem** [comment]
I used your solution because it fixed #2 
Thanks for your help

**Pull request closed without merging**
